# Generated by Django 5.2.7 on 2025-10-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobrador', '0001_initial'),
        ('cuentahabientes', '0001_initial'),
        ('descuento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_recibido', models.IntegerField()),
                ('monto_descuento', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobrador.cobrador')),
                ('cuentahabiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentahabientes.cuentahabiente')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descuento.descuento')),
            ],
        ),
    ]
