# Generated by Django 5.2.7 on 2025-10-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='coment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
