# Generated by Django 5.2.7 on 2025-10-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='coment',
            new_name='comentarios',
        ),
    ]
