# Generated by Django 5.2.7 on 2025-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id_cobrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('usuario', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
