# Generated by Django 5.2.7 on 2025-10-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrador',
            options={'ordering': ['id_cobrador'], 'verbose_name': 'Cobrador', 'verbose_name_plural': 'Cobradores'},
        ),
    ]
