# Generated by Django 5.2.7 on 2025-10-14 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0002_alter_cobrador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 14, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobrador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cobrador',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('cobrador', 'Cobrador')], default='cobrador', max_length=20),
        ),
    ]
