# Generated by Django 5.2.7 on 2026-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrador',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('presidente', 'presidente'), ('cobrador', 'Cobrador'), ('secretario', 'Secretario'), ('tesorero_jr', 'Tesorero Jr'), ('tesorero_sr', 'Tesorero Sr')], default='cobrador', max_length=20),
        ),
    ]
