# Generated by Django 5.2.7 on 2025-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
