# Generated by Django 5.2.7 on 2025-10-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentahabientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cargo', models.CharField(max_length=150)),
                ('monto_cargo', models.IntegerField()),
                ('fecha_cargo', models.DateField()),
                ('cuentahabiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentahabientes.cuentahabiente')),
            ],
        ),
    ]
