# Generated by Django 5.2.7 on 2026-01-22 22:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='saldo_restante_cargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
