# Generated by Django 5.2.7 on 2026-02-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_cargo_saldo_restante_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id_tipo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo_cargo_texto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargos.tipocargo'),
        ),
    ]
