# Generated by Django 5.2.7 on 2026-02-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_tipocargo_cargo_tipo_cargo_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargos.tipocargo'),
        ),
    ]
