# Generated by Django 5.2.7 on 2026-02-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0005_alter_cargo_tipo_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='tipo_cargo_texto',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargos.tipocargo'),
        ),
    ]
