# Generated by Django 5.2.7 on 2026-02-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0006_remove_cargo_tipo_cargo_texto_alter_cargo_tipo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='TipoCargo',
        ),
    ]
