# Generated by Django 5.2.7 on 2026-02-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0007_alter_cargo_tipo_cargo_delete_tipocargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='monto_cargo',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='cargos.tipocargo'),
        ),
    ]
