# Generated by Django 5.2.7 on 2026-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0008_tipocargo_remove_cargo_monto_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocargo',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipocargo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
