# Generated by Django 5.2.7 on 2026-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0009_tipocargo_automatico_alter_tipocargo_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
