# Generated by Django 5.2.7 on 2026-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'ordering': ['nombre_calle'],
            },
        ),
    ]
