# Generated by Django 5.2.7 on 2026-02-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('folio_corte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('total_pagos_normales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagos_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gran_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cobrador_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_realizados', to='cobrador.cobrador')),
            ],
            options={
                'db_table': 'CorteCaja',
                'ordering': ['-folio_corte'],
            },
        ),
    ]
