# Generated by Django 5.2.7 on 2026-02-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
        ('corte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortecaja',
            name='cobrador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_realizados', to='cobrador.cobrador'),
        ),
    ]
