# Generated by Django 5.2.7 on 2026-03-20 03:28

import corte.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0006_alter_cobrador_role'),
        ('corte', '0002_alter_cortecaja_cobrador_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCajaJr',
            fields=[
                ('folio_corte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_pagos_normales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagos_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gran_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=corte.models.upload_corte_jr_pdf)),
                ('validado', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('cobrador', models.ForeignKey(limit_choices_to={'role': 'tesorero_jr'}, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_jr_generados', to='cobrador.cobrador')),
                ('validado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'tesorero_sr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_jr_validados', to='cobrador.cobrador')),
            ],
            options={
                'verbose_name': 'Corte de Caja Jr',
                'verbose_name_plural': 'Cortes de Caja Jr',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
