# Generated by Django 5.2.7 on 2026-03-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0004_alter_cortecajajr_table_cortecajasr'),
        ('corte', '0004_alter_cortecajajr_validado_por_and_more'),
    ]

    operations = [
    ]
