# Generated by Django 5.2.7 on 2026-03-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0006_alter_cobrador_role'),
        ('corte', '0005_merge_20260324_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortecajajr',
            name='validado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tesorero_sr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_jr_validados', to='cobrador.cobrador'),
        ),
    ]
