# Generated by Django 5.2.7 on 2025-10-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentahabiente',
            fields=[
                ('id_cuentahabiente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('ap', models.CharField(max_length=50)),
                ('am', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=256)),
                ('numero', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('deuda', models.CharField(max_length=20)),
                ('saldo_pendiente', models.IntegerField()),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colonia.colonia')),
            ],
        ),
    ]
