# Generated by Django 5.2.7 on 2025-10-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0002_cuentahabiente_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaHistorial',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_contrato', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('nombre_descuento', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'vista_historial_api',
                'ordering': ['-fecha_pago', 'numero_contrato'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaPagos',
            fields=[
                ('numero_contrato', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('nombre_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('anio', models.IntegerField()),
                ('pagos_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus_deuda', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vista_pagos',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='cuentahabiente',
            name='deuda',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('corriente', 'Corriente'), ('rezagado', 'Rezagado'), ('adeudo', 'Adeudo')], default='adeudo', max_length=20),
        ),
    ]
