# Generated by Django 5.2.7 on 2025-10-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0003_vistahistorial_vistapagos_alter_cuentahabiente_deuda'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vistahistorial',
            table='vista_historial',
        ),
    ]
