# Generated by Django 5.2.7 on 2025-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0004_alter_vistahistorial_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaDeudores',
            fields=[
                ('id', models.BigIntegerField(db_column='id_cuentahabiente', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('monto_total', models.IntegerField()),
                ('estatus', models.CharField(max_length=20)),
                ('nombre_colonia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vista_deudores',
                'managed': False,
            },
        ),
    ]
