# Generated by Django 5.2.7 on 2025-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0005_vistadeudores'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaProgreso',
            fields=[
                ('numero_contrato', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('estatus', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('progreso', models.CharField(max_length=4)),
                ('id_cuentahabiente', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vista_progreso',
                'ordering': ['numero_contrato'],
                'managed': False,
            },
        ),
    ]
