# Generated by Django 5.2.7 on 2025-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0006_vistaprogreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id_cuentahabiente', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_contrato', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('saldo_pendiente', models.IntegerField()),
                ('deuda', models.CharField(max_length=20)),
                ('fecha_pago', models.DateField()),
                ('monto_recibido', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
