# Generated by Django 5.2.7 on 2026-01-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0007_estadocuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocuenta',
            options={'managed': False},
        ),
    ]
