# Generated by Django 5.2.7 on 2026-01-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0008_alter_estadocuenta_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadocuenta',
            table='estado_cuenta',
        ),
    ]
