# Generated by Django 5.2.7 on 2026-01-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
        ('cuentahabientes', '0009_alter_estadocuenta_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCuentahabientes',
            fields=[
                ('id_cuentahabiente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('nombre_colonia', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'r_cuentahabientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CierreAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_anuales', to='cobrador.cobrador')),
            ],
            options={
                'db_table': 'cierre_anual',
            },
        ),
    ]
