# Generated by Django 5.2.7 on 2026-01-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0010_rcuentahabientes_cierreanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreanual',
            name='anio',
            field=models.BooleanField(unique=True),
        ),
    ]
