# Generated by Django 5.2.7 on 2026-01-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0011_alter_cierreanual_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreanual',
            name='anio',
            field=models.IntegerField(unique=True),
        ),
    ]
