# Generated by Django 5.2.7 on 2026-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0013_alter_cuentahabiente_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuentaResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuentahabiente', models.IntegerField()),
                ('numero_contrato', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('nombre_servicio', models.CharField(max_length=255, null=True)),
                ('estatus', models.CharField(max_length=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'estado_cuenta_resumen',
                'managed': False,
            },
        ),
    ]
