# Generated by Django 5.2.7 on 2026-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0013_add_calle_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentahabiente',
            name='calle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
