# Generated by Django 5.2.7 on 2026-03-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0014_alter_cuentahabiente_calle'),
    ]

    operations = [
        # 1. Eliminar la vista que bloquea el cambio
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS estado_cuenta;",
            reverse_sql=""  # no es necesario revertirla aquí
        ),

        # 2. Alterar el campo
        migrations.AlterField(
            model_name='cuentahabiente',
            name='numero',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),

        # 3. Volver a crear la vista con el tipo ya cambiado
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE VIEW public.estado_cuenta
                AS SELECT c.id_cuentahabiente,
                    c.numero_contrato,
                    concat(c.nombres, ' ', c.ap, ' ', c.am) AS nombre,
                    concat(c.calle, ' ', c.numero) AS direccion,
                    c.telefono,
                    c.saldo_pendiente,
                    c.deuda,
                    p.fecha_pago,
                    p.monto_recibido,
                    p.anio
                    FROM cuentahabientes_cuentahabiente c
                        JOIN pagos_pago p ON p.cuentahabiente_id = c.id_cuentahabiente
                ORDER BY c.id_cuentahabiente, p.fecha_pago;
            """,
            reverse_sql="DROP VIEW IF EXISTS estado_cuenta;"
        ),
    ]