# Generated by Django 5.2.7 on 2026-04-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentahabientes', '0014_estadocuentaresumen'),
        ('cuentahabientes', '0015_alter_cuentahabiente_numero'),
    ]

    operations = [
    ]
