# Generated by Django 5.2.7 on 2026-05-19 15:50

import tesoreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=tesoreria.models.upload_comprobante_egreso),
        ),
    ]
