# Generated by Django 5.2.7 on 2026-01-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentahabientes', '0012_alter_cierreanual_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCargos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('cuentahabiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentahabientes.cuentahabiente')),
            ],
            options={
                'db_table': 'pagos_cargos',
            },
        ),
    ]
