# Generated by Django 5.2.7 on 2026-01-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
        ('pagos_cargos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocargos',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cobrador.cobrador'),
        ),
    ]
