# Generated by Django 5.2.7 on 2026-01-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_cargo_saldo_restante_cargo'),
        ('pagos_cargos', '0003_alter_pagocargos_cobrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocargos',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargos.cargo'),
        ),
    ]
