# Generated by Django 5.2.7 on 2026-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_cargos', '0004_pagocargos_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocargos',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
