# Generated by Django 5.2.7 on 2025-10-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['id_tipo_servicio'],
            },
        ),
    ]
