# Generated by Django 5.2.7 on 2026-03-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calles', '0001_initial'),
        ('cobrador', '0006_alter_cobrador_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='calles.calle')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_asignados', to='cobrador.cobrador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='cobradores',
            field=models.ManyToManyField(related_name='equipos', through='equipos.EquipoCobrador', to='cobrador.cobrador'),
        ),
        migrations.AddConstraint(
            model_name='equipocobrador',
            constraint=models.UniqueConstraint(fields=('equipo', 'cobrador'), name='uniq_equipo_cobrador'),
        ),
    ]
