# Generated by Django 5.2.7 on 2026-03-19 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrador', '0006_alter_cobrador_role'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipocobrador',
            name='cobrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_asignado', to='cobrador.cobrador'),
        ),
    ]
