# Generated by Django 5.2.7 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocobrador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipocobrador',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
