# Generated by Django 5.2.7 on 2026-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipocobrador_activo_equipocobrador_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre_equipo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
