# Generated by Django 5.2.7 on 2025-10-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobrador', '0001_initial'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobrador.cobrador')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
        ),
    ]
