# Generated by Django 5.2.7 on 2025-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('cobrador', '0003_cobrador_created_at_cobrador_is_active_cobrador_role'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fecha_asignacion', '-id_asignacion']},
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(fields=('cobrador', 'sector', 'fecha_asignacion'), name='uniq_cobrador_sector_fecha'),
        ),
    ]
